package co.com.fcv.training.citas.adapter.persistence;

import co.com.fcv.training.citas.application.Ports;
import co.com.fcv.training.citas.application.SchedulingService;
import co.com.fcv.training.citas.application.SchedulingService.Appointment;
import co.com.fcv.training.citas.application.SchedulingService.Available;
import co.com.fcv.training.citas.application.SchedulingService.Block;
import co.com.fcv.training.citas.application.SchedulingService.PendingAppointment;
import co.com.fcv.training.citas.application.SchedulingService.Professional;
import co.com.fcv.training.citas.application.SchedulingService.Specialty;
import co.com.fcv.training.citas.application.SchedulingFailure;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.*;
import java.util.*;

@Repository
class SchedulingJdbcAdapter implements Ports.Scheduling {
    private final JdbcTemplate jdbc; private final Clock clock; private final ApplicationEventPublisher events;
    SchedulingJdbcAdapter(JdbcTemplate jdbc, Clock clock, ApplicationEventPublisher events) { this.jdbc=jdbc; this.clock=clock; this.events=events; }

    public List<Map<String,Object>> catalog(String name) {
        String sql = switch(name) {
            case "locations" -> "select id,code,name,address,city,department from locations where active=true order by name";
            case "appointment-statuses" -> "select id,code,name,is_terminal as terminal from appointment_statuses order by id";
            case "reschedule-statuses" -> "select id,code,name,is_terminal as terminal from reschedule_request_statuses order by id";
            case "roles" -> "select id,code,name,description from roles order by id";
            case "regimes" -> "select id,code,name from insurance_regimes order by name";
            case "plans" -> "select p.id,p.code,p.name,p.eps_id as epsId,p.regime_id as regimeId from eps_plans p where p.active=true order by p.name";
            default -> throw new IllegalArgumentException("Catálogo no soportado");
        }; return jdbc.queryForList(sql);
    }
    public List<Specialty> specialties(boolean activeOnly) { return jdbc.query("select id,code,name,appointment_duration_minutes,is_general,active from specialties " + (activeOnly?"where active=true ":"") + "order by name", (r,n)->new Specialty(r.getLong(1),r.getString(2),r.getString(3),r.getInt(4),r.getBoolean(5),r.getBoolean(6))); }
    public List<Professional> professionals() { return jdbc.query("select p.id,concat(u.first_name,' ',u.last_name),p.professional_code,p.license_number,p.active,group_concat(distinct ps.specialty_id order by ps.specialty_id),group_concat(distinct pl.location_id order by pl.location_id),max(case when ps.is_primary then ps.specialty_id end) from professionals p join users u on u.id=p.user_id left join professional_specialties ps on ps.professional_id=p.id and ps.active=true left join professional_locations pl on pl.professional_id=p.id and pl.active=true group by p.id,u.first_name,u.last_name,p.professional_code,p.license_number,p.active order by u.first_name,u.last_name", (r,n) -> new Professional(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getBoolean(5),ids(r.getString(6)),ids(r.getString(7)),r.getObject(8)==null?null:r.getLong(8))); }
    @Transactional public Specialty createSpecialty(String code,String name,int duration,boolean general) { validateDuration(duration); Long id=insert("insert into specialties(code,name,appointment_duration_minutes,is_general,requires_admin_approval,active) values (?,?,?,?,?,true)",code,name,duration,general,!general); return specialty(id); }
    @Transactional public Specialty updateSpecialty(Long id,String name,Integer duration,Boolean active) { Specialty old=specialtyForAdministration(id); int d=duration==null?old.durationMinutes():duration; validateDuration(d); jdbc.update("update specialties set name=?,appointment_duration_minutes=?,active=? where id=?", name==null?old.name():name,d,active==null?old.active():active,id); return specialtyForAdministration(id); }
    public Long createProfessional(String first,String last,String docType,String doc,String email,String phone,String passwordHash,String code,String license) {
        Long user=insert("insert into users(first_name,last_name,document_type,document_number,email,phone,password_hash,active,email_verified) values (?,?,?,?,?,?,?,true,false)",first,last,docType,doc,email,phone,passwordHash);
        jdbc.update("insert into user_roles(user_id,role_id) select ?,id from roles where code='PROFESSIONAL'",user);
        return insert("insert into professionals(user_id,professional_code,license_number,active) values (?,?,?,true)",user,code,license);
    }
    @Transactional public void setProfessionalSpecialties(Long professionalId,List<Long> ids,Long primary) { requireProfessional(professionalId); if(ids==null||ids.isEmpty()||primary==null||!ids.contains(primary)) throw new IllegalArgumentException("Asignación primaria requerida"); for(Long id:ids) { if(count("select count(*) from specialties where id=?",id)==0) throw notFound("Especialidad"); } jdbc.update("delete from professional_specialties where professional_id=?",professionalId); for(Long id:ids) jdbc.update("insert into professional_specialties(professional_id,specialty_id,is_primary,active) values (?,?,?,true)",professionalId,id,id.equals(primary)); }
    @Transactional public void setProfessionalLocations(Long professionalId,List<Long> ids) { requireProfessional(professionalId); if(ids==null||ids.isEmpty()||ids.size()>2) throw new IllegalArgumentException("Debe asignar una o dos sedes"); for(Long id:ids) if(count("select count(*) from locations where id=? and active=true",id)==0) throw notFound("Sede"); jdbc.update("delete from professional_locations where professional_id=?",professionalId); for(Long id:ids) jdbc.update("insert into professional_locations(professional_id,location_id,active) values (?,?,true)",professionalId,id); }
    public void setProfessionalActive(Long id,boolean active) { if(jdbc.update("update professionals set active=? where id=?",active,id)==0) throw notFound("Profesional"); }
    @Transactional public Block createBlock(Long userId,Long locationId,LocalDate date,LocalTime start,LocalTime end) { Long professional=professionalForUser(userId); validateBlock(professional,locationId,date,start,end,null); Long id=insert("insert into availability_blocks(professional_id,location_id,available_date,start_time,end_time,active) values (?,?,?,?,?,true)",professional,locationId,date,start,end); createSlots(id,date,start,end); return new Block(id,locationId,date,start,end); }
    public List<Block> blocks(Long userId,LocalDate date,Long location) { Long professional=professionalForUser(userId); String sql="select id,location_id,available_date,start_time,end_time from availability_blocks where professional_id=? and active=true"; List<Object> ps=new ArrayList<>(List.of(professional)); if(date!=null){sql+=" and available_date=?";ps.add(date);}if(location!=null){sql+=" and location_id=?";ps.add(location);}sql+=" order by available_date,start_time";return jdbc.query(sql,(r,n)->new Block(r.getLong(1),r.getLong(2),r.getObject(3,LocalDate.class),r.getObject(4,LocalTime.class),r.getObject(5,LocalTime.class)),ps.toArray()); }
    @Transactional public Block updateBlock(Long userId,Long id,Long location,LocalDate date,LocalTime start,LocalTime end) { Long professional=professionalForUser(userId); Block old=jdbc.query("select id,location_id,available_date,start_time,end_time from availability_blocks where id=? and professional_id=? and active=true for update",(r,n)->new Block(r.getLong(1),r.getLong(2),r.getObject(3,LocalDate.class),r.getObject(4,LocalTime.class),r.getObject(5,LocalTime.class)),id,professional).stream().findFirst().orElseThrow(()->notFound("Bloque")); if(!old.date().isAfter(LocalDate.now(clock))) throw conflict("El bloque ya no es futuro"); if(count("select count(*) from professional_slots where availability_block_id=? and appointment_id is not null",id)>0) throw conflict("El bloque tiene citas comprometidas"); Long lid=location==null?old.locationId():location; LocalDate d=date==null?old.date():date; LocalTime s=start==null?old.start():start,e=end==null?old.end():end; validateBlock(professional,lid,d,s,e,id); jdbc.update("update availability_blocks set location_id=?,available_date=?,start_time=?,end_time=? where id=?",lid,d,s,e,id);jdbc.update("delete from professional_slots where availability_block_id=?",id);createSlots(id,d,s,e);return new Block(id,lid,d,s,e); }
    @Transactional public void deleteBlock(Long userId,Long id) { Long professional=professionalForUser(userId); if(count("select count(*) from availability_blocks where id=? and professional_id=? and active=true",id,professional)==0) throw notFound("Bloque");if(count("select count(*) from availability_blocks where id=? and available_date<=?",id,LocalDate.now(clock))>0) throw conflict("El bloque ya no es futuro");if(count("select count(*) from professional_slots where availability_block_id=? and appointment_id is not null",id)>0)throw conflict("El bloque tiene citas comprometidas");jdbc.update("delete from professional_slots where availability_block_id=?",id);jdbc.update("update availability_blocks set active=false where id=?",id); }
    public List<Available> availability(Long location,Long specialty,Long professional,LocalDate date) { Specialty s=specialty(specialty); String sql="select ps.start_at,ps.end_at,p.id,u.first_name,u.last_name from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id join professionals p on p.id=b.professional_id join users u on u.id=p.user_id join professional_specialties x on x.professional_id=p.id and x.specialty_id=? and x.active=true join professional_locations l on l.professional_id=p.id and l.location_id=b.location_id and l.active=true where b.active=true and p.active=true and ps.appointment_id is null and b.location_id=? and b.available_date=?"+(professional==null?"":" and p.id=?")+" order by p.id,ps.start_at"; List<Object> args=new ArrayList<>(List.of(specialty,location,date));if(professional!=null)args.add(professional);List<Available> raw=jdbc.query(sql,(r,n)->new Available(r.getLong(3),r.getString(4)+" "+r.getString(5),r.getObject(1,LocalDateTime.class),r.getObject(2,LocalDateTime.class)),args.toArray());if(s.durationMinutes()==30)return raw;List<Available> out=new ArrayList<>();for(int i=0;i+1<raw.size();i++){Available a=raw.get(i),b=raw.get(i+1);if(a.professionalId().equals(b.professionalId())&&a.endAt().equals(b.startAt()))out.add(new Available(a.professionalId(),a.professionalName(),a.startAt(),b.endAt()));}return out; }
    public List<SchedulingService.MyAppointment> appointments(Long user, String status, LocalDate date) { String sql="select a.id,a.professional_id,a.specialty_id,a.location_id,concat(pu.first_name,' ',pu.last_name),sp.name,l.name,a.scheduled_start_at,a.scheduled_end_at,sp.appointment_duration_minutes,st.code,(select h.reason from appointment_status_history h join appointment_statuses hs on hs.id=h.status_id where h.appointment_id=a.id and hs.code='REJECTED' and h.reason is not null order by h.changed_at desc limit 1),rr.id,rst.code,rr.requested_start_at,rr.decision_reason from appointments a join professionals p on p.id=a.professional_id join users pu on pu.id=p.user_id join specialties sp on sp.id=a.specialty_id join locations l on l.id=a.location_id join appointment_statuses st on st.id=a.status_id left join reschedule_requests rr on rr.id=(select max(rx.id) from reschedule_requests rx where rx.appointment_id=a.id) left join reschedule_request_statuses rst on rst.id=rr.status_id where a.patient_user_id=?"; List<Object> args=new ArrayList<>(List.of(user)); if(status!=null){sql+=" and st.code=?";args.add(status);} if(date!=null){sql+=" and date(a.scheduled_start_at)=?";args.add(date);} sql+=" order by a.scheduled_start_at desc,a.id desc"; return jdbc.query(sql,(r,n)->new SchedulingService.MyAppointment(r.getLong(1),r.getLong(2),r.getLong(3),r.getLong(4),r.getString(5),r.getString(6),r.getString(7),r.getObject(8,LocalDateTime.class),r.getObject(9,LocalDateTime.class),r.getInt(10),r.getString(11),r.getString(12),r.getObject(13,Long.class),r.getString(14),r.getObject(15,LocalDateTime.class),r.getString(16)),args.toArray()); }
    @Transactional
    public Appointment reserve(Long user, Long professional, Long location, Long specialtyId, LocalDateTime start, String reason) {
        Specialty specialty = specialty(specialtyId);
        int minutes = specialty.durationMinutes();
        LocalDateTime end = start.plusMinutes(minutes);
        if (start.isBefore(LocalDateTime.now(clock))) throw new IllegalArgumentException("La cita debe ser futura");
        if (count("select count(*) from professionals p join professional_specialties x on x.professional_id=p.id and x.specialty_id=? and x.active=true join professional_locations l on l.professional_id=p.id and l.location_id=? and l.active=true where p.id=? and p.active=true and ?=(select 1)", specialtyId, location, professional, 1) == 0) throw conflict("Profesional no disponible para la selección");

        List<Long> slots = jdbc.queryForList("select ps.id from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id where b.professional_id=? and b.location_id=? and b.active=true and ps.appointment_id is null and ps.start_at>=? and ps.end_at<=? order by ps.start_at for update", Long.class, professional, location, start, end);
        if (slots.size() != minutes / 30) throw conflict("Franja no disponible");
        String placeholders = String.join(",", Collections.nCopies(slots.size(), "?"));
        List<LocalDateTime> times = jdbc.query("select ps.start_at from professional_slots ps where ps.id in (" + placeholders + ") order by ps.start_at", (r,n) -> r.getObject(1, LocalDateTime.class), slots.toArray());
        for (int i = 1; i < times.size(); i++) if (!times.get(i - 1).plusMinutes(30).equals(times.get(i))) throw conflict("Slots no consecutivos");

        String status = specialty.general() ? "APPROVED" : "REQUESTED";
        Long affiliation = jdbc.query("select id from user_insurance_affiliations where user_id=? and is_current=true order by id desc limit 1", (r,n) -> r.getLong(1), user).stream().findFirst().orElse(null);
        Long statusId = statusId(status);
        Long appointment = insert("insert into appointments(patient_user_id,professional_id,location_id,specialty_id,insurance_affiliation_id,status_id,reason,scheduled_start_at,scheduled_end_at,created_by_user_id,approved_at) values (?,?,?,?,?,?,?,?,?,?,?)", user, professional, location, specialtyId, affiliation, statusId, reason, start, end, user, specialty.general() ? LocalDateTime.now(clock) : null);
        int assigned = jdbc.update("update professional_slots set appointment_id=? where appointment_id is null and id in (" + placeholders + ")", concat(appointment, slots));
        if (assigned != slots.size()) throw conflict("Franja ya reservada");
        jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)", appointment, statusId, specialty.general() ? null : user, specialty.general() ? "SYSTEM" : "USER", specialty.general() ? "Aprobación automática" : reason);
        return new Appointment(appointment, status, start, end);
    }
    @Transactional public Appointment cancel(Long user, Long appointment) { Map<String,Object> a=jdbc.queryForList("select a.scheduled_start_at,a.scheduled_end_at,st.code,st.is_terminal from appointments a join appointment_statuses st on st.id=a.status_id where a.id=? and a.patient_user_id=? for update",appointment,user).stream().findFirst().orElseThrow(()->notFound("Cita")); if(Boolean.TRUE.equals(a.get("is_terminal"))||!((LocalDateTime)a.get("scheduled_start_at")).isAfter(LocalDateTime.now(clock)))throw conflict("La cita no puede cancelarse"); jdbc.update("update appointments set status_id=? where id=?",statusId("CANCELLED"),appointment);jdbc.update("update professional_slots set appointment_id=null where appointment_id=?",appointment);jdbc.update("update reschedule_requests set status_id=? where appointment_id=? and status_id=?",rescheduleStatusId("CANCELLED"),appointment,rescheduleStatusId("PENDING"));jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",appointment,statusId("CANCELLED"),user,"USER","Cancelada por usuario");events.publishEvent(new Ports.AppointmentStatusChanged(appointment,(String)a.get("code"),"CANCELLED","USER",user,LocalDateTime.now(clock)));return new Appointment(appointment,"CANCELLED",(LocalDateTime)a.get("scheduled_start_at"),(LocalDateTime)a.get("scheduled_end_at")); }
    @Transactional public SchedulingService.RescheduleRequest requestReschedule(Long user, Long appointment, Long location, LocalDateTime start) { Map<String,Object> a=jdbc.queryForList("select a.professional_id,a.specialty_id,a.scheduled_start_at,a.scheduled_end_at,st.code,sp.appointment_duration_minutes from appointments a join appointment_statuses st on st.id=a.status_id join specialties sp on sp.id=a.specialty_id where a.id=? and a.patient_user_id=? for update",appointment,user).stream().findFirst().orElseThrow(()->notFound("Cita"));if(!"APPROVED".equals(a.get("code"))||!((LocalDateTime)a.get("scheduled_start_at")).isAfter(LocalDateTime.now(clock))||!start.isAfter(LocalDateTime.now(clock)))throw conflict("La cita no es elegible para reprogramación");if(count("select count(*) from reschedule_requests r join reschedule_request_statuses s on s.id=r.status_id where r.appointment_id=? and s.code='PENDING'",appointment)>0)throw conflict("La cita ya tiene una reprogramación pendiente");Long professional=((Number)a.get("professional_id")).longValue();int minutes=((Number)a.get("appointment_duration_minutes")).intValue();LocalDateTime end=start.plusMinutes(minutes);if(count("select count(*) from professional_locations where professional_id=? and location_id=? and active=true",professional,location)==0)throw conflict("El profesional no atiende en la sede seleccionada");List<Long> slots=jdbc.queryForList("select ps.id from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id where b.professional_id=? and b.location_id=? and b.active=true and ps.appointment_id is null and ps.start_at>=? and ps.end_at<=? order by ps.start_at for update",Long.class,professional,location,start,end);if(slots.size()!=minutes/30)throw conflict("Franja no disponible");String marks=String.join(",",Collections.nCopies(slots.size(),"?"));List<Object> update=new ArrayList<>();update.add(appointment);update.addAll(slots);if(jdbc.update("update professional_slots set appointment_id=? where appointment_id is null and id in ("+marks+")",update.toArray())!=slots.size())throw conflict("Franja no disponible");Long id=insert("insert into reschedule_requests(appointment_id,requested_by_user_id,requested_location_id,status_id,previous_start_at,previous_end_at,requested_start_at,requested_end_at) values (?,?,?,?,?,?,?,?)",appointment,user,location,rescheduleStatusId("PENDING"),a.get("scheduled_start_at"),a.get("scheduled_end_at"),start,end);return new SchedulingService.RescheduleRequest(id,"PENDING"); }
    public List<SchedulingService.PendingReschedule> pendingReschedules(){return jdbc.query("select r.id,a.id,concat(patient.first_name,' ',patient.last_name),concat(professional.first_name,' ',professional.last_name),s.name,l.name,r.previous_start_at,r.requested_start_at,r.requested_end_at from reschedule_requests r join reschedule_request_statuses rs on rs.id=r.status_id join appointments a on a.id=r.appointment_id join users patient on patient.id=a.patient_user_id join professionals p on p.id=a.professional_id join users professional on professional.id=p.user_id join specialties s on s.id=a.specialty_id join locations l on l.id=r.requested_location_id where rs.code='PENDING' order by r.created_at",(r,n)->new SchedulingService.PendingReschedule(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getObject(7,LocalDateTime.class),r.getObject(8,LocalDateTime.class),r.getObject(9,LocalDateTime.class)));}
    @Transactional public SchedulingService.RescheduleRequest decideReschedule(Long admin,Long request,String decision,String reason){if(!Set.of("APPROVE","REJECT").contains(decision))throw new IllegalArgumentException("Decisión inválida");if("REJECT".equals(decision)&&(reason==null||reason.isBlank()))throw new IllegalArgumentException("Motivo de rechazo obligatorio");Map<String,Object> r=jdbc.queryForList("select r.appointment_id,r.requested_location_id,r.previous_start_at,r.previous_end_at,r.requested_start_at,r.requested_end_at,a.status_id,rs.code from reschedule_requests r join reschedule_request_statuses rs on rs.id=r.status_id join appointments a on a.id=r.appointment_id where r.id=? for update",request).stream().findFirst().orElseThrow(()->notFound("Solicitud de reprogramación"));if(!"PENDING".equals(r.get("code")))throw conflict("La solicitud de reprogramación ya fue resuelta");Long appointment=((Number)r.get("appointment_id")).longValue();if(count("select count(*) from appointments a join appointment_statuses s on s.id=a.status_id where a.id=? and s.code='APPROVED'",appointment)==0)throw conflict("La cita ya no permite reprogramación");String status="APPROVE".equals(decision)?"APPROVED":"REJECTED";if("APPROVE".equals(decision)){jdbc.update("update professional_slots set appointment_id=null where appointment_id=? and start_at>=? and end_at<=?",appointment,r.get("previous_start_at"),r.get("previous_end_at"));jdbc.update("update appointments set location_id=?,scheduled_start_at=?,scheduled_end_at=? where id=?",r.get("requested_location_id"),r.get("requested_start_at"),r.get("requested_end_at"),appointment);jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",appointment,statusId("APPROVED"),admin,"ADMIN","Reprogramación aprobada");}else jdbc.update("update professional_slots set appointment_id=null where appointment_id=? and start_at>=? and end_at<=?",appointment,r.get("requested_start_at"),r.get("requested_end_at"));jdbc.update("update reschedule_requests set status_id=?,decision_reason=?,decided_by_user_id=?,decided_at=? where id=?",rescheduleStatusId(status),reason,admin,LocalDateTime.now(clock),request);return new SchedulingService.RescheduleRequest(request,status);}
    public List<PendingAppointment> pending() { return jdbc.query("select a.id,concat(patient.first_name,' ',patient.last_name),concat(professional_user.first_name,' ',professional_user.last_name),s.name,l.name,a.scheduled_start_at,a.scheduled_end_at,s.appointment_duration_minutes from appointments a join appointment_statuses st on st.id=a.status_id join users patient on patient.id=a.patient_user_id join professionals p on p.id=a.professional_id join users professional_user on professional_user.id=p.user_id join specialties s on s.id=a.specialty_id join locations l on l.id=a.location_id where st.code='REQUESTED' and s.is_general=false order by a.scheduled_start_at", (r,n) -> new PendingAppointment(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getObject(6,LocalDateTime.class),r.getObject(7,LocalDateTime.class),r.getInt(8))); }
    @Transactional public Appointment decide(Long admin,Long appointment,String decision,String reason) { if(!Set.of("APPROVE","REJECT").contains(decision))throw new IllegalArgumentException("Decisión inválida"); if("REJECT".equals(decision)&&(reason==null||reason.isBlank()))throw new IllegalArgumentException("Motivo de rechazo obligatorio"); Map<String,Object> a=jdbc.queryForList("select a.id,a.scheduled_start_at,a.scheduled_end_at,s.code,sp.is_general from appointments a join appointment_statuses s on s.id=a.status_id join specialties sp on sp.id=a.specialty_id where a.id=? for update",appointment).stream().findFirst().orElseThrow(()->notFound("Cita"));if(!"REQUESTED".equals(a.get("code"))||Boolean.TRUE.equals(a.get("is_general")))throw conflict("La cita no está pendiente de decisión administrativa");String status="APPROVE".equals(decision)?"APPROVED":"REJECTED";Long sid=statusId(status);jdbc.update("update appointments set status_id=?,approved_by_user_id=?,approved_at=? where id=?",sid,admin,LocalDateTime.now(clock),appointment);if("REJECTED".equals(status))jdbc.update("update professional_slots set appointment_id=null where appointment_id=?",appointment);jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",appointment,sid,admin,"ADMIN",reason);events.publishEvent(new Ports.AppointmentStatusChanged(appointment,"REQUESTED",status,"ADMIN",admin,LocalDateTime.now(clock)));return new Appointment(appointment,status,(LocalDateTime)a.get("scheduled_start_at"),(LocalDateTime)a.get("scheduled_end_at")); }
    public List<SchedulingService.Eps> epsList(boolean activeOnly) { return jdbc.query("select id,code,name,active from eps " + (activeOnly?"where active=true ":"") + "order by name", (r,n)->new SchedulingService.Eps(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4))); }
    @Transactional public SchedulingService.Eps createEps(String code,String name) { if(count("select count(*) from eps where code=?",code)>0) throw conflict("EPS ya existe"); Long id=insert("insert into eps(code,name,active) values (?,?,true)",code,name); return epsForAdministration(id); }
    @Transactional public SchedulingService.Eps updateEps(Long id,String name,Boolean active) { SchedulingService.Eps old=epsForAdministration(id); jdbc.update("update eps set name=?,active=? where id=?", name==null?old.name():name, active==null?old.active():active, id); return epsForAdministration(id); }
    public List<SchedulingService.EpsPlan> epsPlans(Long epsId) { String sql="select id,eps_id,regime_id,code,name,active from eps_plans"+(epsId==null?"":" where eps_id=?")+" order by name"; return epsId==null ? jdbc.query(sql,(r,n)->new SchedulingService.EpsPlan(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getBoolean(6))) : jdbc.query(sql,(r,n)->new SchedulingService.EpsPlan(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getBoolean(6)),epsId); }
    @Transactional public SchedulingService.EpsPlan createEpsPlan(Long epsId,Long regimeId,String code,String name) { SchedulingService.Eps eps=epsForAdministration(epsId); if(!eps.active()) throw conflict("La EPS debe estar activa"); if(count("select count(*) from insurance_regimes where id=?",regimeId)==0) throw notFound("Régimen"); if(count("select count(*) from eps_plans where eps_id=? and code=?",epsId,code)>0) throw conflict("El plan ya existe para esta EPS"); Long id=insert("insert into eps_plans(eps_id,regime_id,code,name,active) values (?,?,?,?,true)",epsId,regimeId,code,name); return epsPlanForAdministration(id); }
    @Transactional public SchedulingService.EpsPlan updateEpsPlan(Long id,String name,Boolean active) { SchedulingService.EpsPlan old=epsPlanForAdministration(id); jdbc.update("update eps_plans set name=?,active=? where id=?", name==null?old.name():name, active==null?old.active():active, id); return epsPlanForAdministration(id); }
    private SchedulingService.Eps epsForAdministration(Long id){return jdbc.query("select id,code,name,active from eps where id=?",(r,n)->new SchedulingService.Eps(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4)),id).stream().findFirst().orElseThrow(()->notFound("EPS"));}
    private SchedulingService.EpsPlan epsPlanForAdministration(Long id){return jdbc.query("select id,eps_id,regime_id,code,name,active from eps_plans where id=?",(r,n)->new SchedulingService.EpsPlan(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getBoolean(6)),id).stream().findFirst().orElseThrow(()->notFound("Plan de EPS"));}
    public List<SchedulingService.ProfessionalAppointment> professionalAppointments(Long userId, LocalDate from, LocalDate to, Long locationId) {
        Long professional = professionalForUser(userId);
        String sql = "select a.id,concat(pu.first_name,' ',pu.last_name),a.specialty_id,sp.name,a.location_id,l.name,a.scheduled_start_at,a.scheduled_end_at,sp.appointment_duration_minutes,a.reason from appointments a join appointment_statuses st on st.id=a.status_id join users pu on pu.id=a.patient_user_id join specialties sp on sp.id=a.specialty_id join locations l on l.id=a.location_id where a.professional_id=? and st.code='APPROVED'";
        List<Object> args = new ArrayList<>(List.of(professional));
        if (from != null) { sql += " and date(a.scheduled_start_at) >= ?"; args.add(from); }
        if (to != null) { sql += " and date(a.scheduled_start_at) <= ?"; args.add(to); }
        if (locationId != null) { sql += " and a.location_id = ?"; args.add(locationId); }
        sql += " order by a.scheduled_start_at";
        return jdbc.query(sql, (r,n) -> new SchedulingService.ProfessionalAppointment(r.getLong(1), r.getString(2), r.getLong(3), r.getString(4), r.getLong(5), r.getString(6), r.getObject(7,LocalDateTime.class), r.getObject(8,LocalDateTime.class), r.getInt(9), r.getString(10)), args.toArray());
    }
    @Transactional public Appointment closeAppointment(Long user, Long appointment, String result, String reason) {
        if (!Set.of("COMPLETED","NO_SHOW").contains(result)) throw new IllegalArgumentException("Resultado inválido");
        Long professional = professionalForUser(user);
        Map<String,Object> a = jdbc.query("select a.scheduled_start_at,a.scheduled_end_at,st.code from appointments a join appointment_statuses st on st.id=a.status_id where a.id=? and a.professional_id=? for update",
                (r,n) -> Map.<String,Object>of("start", r.getObject(1,LocalDateTime.class), "end", r.getObject(2,LocalDateTime.class), "code", r.getString(3)),
                appointment, professional).stream().findFirst().orElseThrow(() -> notFound("Cita"));
        if (!"APPROVED".equals(a.get("code"))) throw conflict("La cita no está aprobada");
        if (!((LocalDateTime)a.get("end")).isBefore(LocalDateTime.now(clock))) throw conflict("La cita aún no ha finalizado");
        Long sid = statusId(result);
        jdbc.update("update appointments set status_id=? where id=?", sid, appointment);
        jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)", appointment, sid, user, "PROFESSIONAL", reason);
        return new Appointment(appointment, result, (LocalDateTime)a.get("start"), (LocalDateTime)a.get("end"));
    }
    public List<SchedulingService.AppointmentHistoryEntry> history(Long callerId, boolean admin, Long appointmentId) {
        String sql = "select h.id,s.code,h.changed_by_user_id,h.change_source,h.reason,h.changed_at from appointment_status_history h join appointment_statuses s on s.id=h.status_id join appointments a on a.id=h.appointment_id left join professionals p on p.id=a.professional_id where h.appointment_id=? and (?=true or a.patient_user_id=? or p.user_id=?) order by h.changed_at,h.id";
        List<SchedulingService.AppointmentHistoryEntry> rows = jdbc.query(sql,
                (r,n) -> new SchedulingService.AppointmentHistoryEntry(r.getLong(1), r.getString(2), r.getObject(3, Long.class), r.getString(4), r.getString(5), r.getObject(6, LocalDateTime.class)),
                appointmentId, admin, callerId, callerId);
        if (rows.isEmpty()) throw notFound("Cita");
        return rows;
    }
    public List<SchedulingService.UpcomingAppointment> upcoming(LocalDate from, LocalDate to, Long locationId) {
        String sql = "select a.id,concat(pu.first_name,' ',pu.last_name),pu.phone,concat(prof_u.first_name,' ',prof_u.last_name),sp.name,a.location_id,l.name,a.scheduled_start_at,a.scheduled_end_at from appointments a join appointment_statuses st on st.id=a.status_id join users pu on pu.id=a.patient_user_id join professionals p on p.id=a.professional_id join users prof_u on prof_u.id=p.user_id join specialties sp on sp.id=a.specialty_id join locations l on l.id=a.location_id where st.code='APPROVED' and a.scheduled_start_at >= ?";
        List<Object> args = new ArrayList<>();
        args.add(from != null ? LocalDateTime.of(from, LocalTime.MIN) : LocalDateTime.now(clock));
        if (to != null) { sql += " and date(a.scheduled_start_at) <= ?"; args.add(to); }
        if (locationId != null) { sql += " and a.location_id = ?"; args.add(locationId); }
        sql += " order by a.scheduled_start_at";
        return jdbc.query(sql, (r,n) -> new SchedulingService.UpcomingAppointment(r.getLong(1), r.getString(2), r.getString(3), r.getString(4), r.getString(5), r.getLong(6), r.getString(7), r.getObject(8,LocalDateTime.class), r.getObject(9,LocalDateTime.class)), args.toArray());
    }
    public List<SchedulingService.InboxItem> inbox(Long locationId, Long professionalId, Long specialtyId, LocalDate date) {
        String specializedSql = "select a.id,concat(patient.first_name,' ',patient.last_name),concat(professional_user.first_name,' ',professional_user.last_name),s.name,a.location_id,l.name,a.scheduled_start_at,a.scheduled_end_at from appointments a join appointment_statuses st on st.id=a.status_id join users patient on patient.id=a.patient_user_id join professionals p on p.id=a.professional_id join users professional_user on professional_user.id=p.user_id join specialties s on s.id=a.specialty_id join locations l on l.id=a.location_id where st.code='REQUESTED' and s.is_general=false";
        List<Object> specializedArgs = new ArrayList<>();
        if (locationId != null) { specializedSql += " and a.location_id=?"; specializedArgs.add(locationId); }
        if (professionalId != null) { specializedSql += " and a.professional_id=?"; specializedArgs.add(professionalId); }
        if (specialtyId != null) { specializedSql += " and a.specialty_id=?"; specializedArgs.add(specialtyId); }
        if (date != null) { specializedSql += " and date(a.scheduled_start_at)=?"; specializedArgs.add(date); }
        List<SchedulingService.InboxItem> specialized = jdbc.query(specializedSql,
                (r,n) -> new SchedulingService.InboxItem("SPECIALIZED", r.getLong(1), r.getLong(1), r.getString(2), r.getString(3), r.getString(4), r.getLong(5), r.getString(6), r.getObject(7,LocalDateTime.class), r.getObject(8,LocalDateTime.class)),
                specializedArgs.toArray());

        String rescheduleSql = "select r.id,r.appointment_id,concat(patient.first_name,' ',patient.last_name),concat(professional_user.first_name,' ',professional_user.last_name),s.name,r.requested_location_id,l.name,r.requested_start_at,r.requested_end_at from reschedule_requests r join reschedule_request_statuses rs on rs.id=r.status_id join appointments a on a.id=r.appointment_id join users patient on patient.id=a.patient_user_id join professionals p on p.id=a.professional_id join users professional_user on professional_user.id=p.user_id join specialties s on s.id=a.specialty_id join locations l on l.id=r.requested_location_id where rs.code='PENDING'";
        List<Object> rescheduleArgs = new ArrayList<>();
        if (locationId != null) { rescheduleSql += " and r.requested_location_id=?"; rescheduleArgs.add(locationId); }
        if (professionalId != null) { rescheduleSql += " and a.professional_id=?"; rescheduleArgs.add(professionalId); }
        if (specialtyId != null) { rescheduleSql += " and a.specialty_id=?"; rescheduleArgs.add(specialtyId); }
        if (date != null) { rescheduleSql += " and date(r.requested_start_at)=?"; rescheduleArgs.add(date); }
        List<SchedulingService.InboxItem> reschedules = jdbc.query(rescheduleSql,
                (r,n) -> new SchedulingService.InboxItem("RESCHEDULE", r.getLong(1), r.getLong(2), r.getString(3), r.getString(4), r.getString(5), r.getLong(6), r.getString(7), r.getObject(8,LocalDateTime.class), r.getObject(9,LocalDateTime.class)),
                rescheduleArgs.toArray());

        List<SchedulingService.InboxItem> combined = new ArrayList<>(specialized);
        combined.addAll(reschedules);
        combined.sort(Comparator.comparing(SchedulingService.InboxItem::startAt));
        return combined;
    }
    private void validateBlock(Long professional,Long location,LocalDate date,LocalTime start,LocalTime end,Long except) { if(!date.isAfter(LocalDate.now(clock))||!end.isAfter(start)||start.getMinute()%30!=0||end.getMinute()%30!=0)throw new IllegalArgumentException("Bloque futuro y alineado a 30 minutos requerido");if(count("select count(*) from professionals p join professional_locations l on l.professional_id=p.id and l.location_id=? and l.active=true where p.id=? and p.active=true",location,professional)==0)throw conflict("Profesional no habilitado en sede");String q="select count(*) from availability_blocks where professional_id=? and active=true and available_date=? and start_time < ? and end_time > ?"+(except==null?"":" and id<>?");List<Object> x=new ArrayList<>(List.of(professional,date,end,start));if(except!=null)x.add(except);if(count(q,x.toArray())>0)throw conflict("Bloque solapado"); }
    private void createSlots(Long block,LocalDate date,LocalTime start,LocalTime end){for(LocalTime t=start;t.isBefore(end);t=t.plusMinutes(30))jdbc.update("insert into professional_slots(availability_block_id,start_at,end_at) values (?,?,?)",block,LocalDateTime.of(date,t),LocalDateTime.of(date,t.plusMinutes(30)));}
    private List<Long> ids(String values) { return values == null || values.isBlank() ? List.of() : Arrays.stream(values.split(",")).map(Long::valueOf).toList(); }
    private Long professionalForUser(Long user){return jdbc.query("select id from professionals where user_id=? and active=true",(r,n)->r.getLong(1),user).stream().findFirst().orElseThrow(()->notFound("Profesional"));}
    private void requireProfessional(Long id){if(count("select count(*) from professionals where id=?",id)==0)throw notFound("Profesional");}
    private Specialty specialty(Long id){ Specialty specialty=specialtyForAdministration(id); if(!specialty.active()) throw notFound("Especialidad activa"); return specialty; }
    private Specialty specialtyForAdministration(Long id){return jdbc.query("select id,code,name,appointment_duration_minutes,is_general,active from specialties where id=?",(r,n)->new Specialty(r.getLong(1),r.getString(2),r.getString(3),r.getInt(4),r.getBoolean(5),r.getBoolean(6)),id).stream().findFirst().orElseThrow(()->notFound("Especialidad"));}
    private Long statusId(String code){return jdbc.query("select id from appointment_statuses where code=?",(r,n)->r.getLong(1),code).stream().findFirst().orElseThrow(()->new IllegalStateException("Estado faltante"));}
    private Long rescheduleStatusId(String code){return jdbc.query("select id from reschedule_request_statuses where code=?",(r,n)->r.getLong(1),code).stream().findFirst().orElseThrow(()->new IllegalStateException("Estado de reprogramación faltante"));}
    private Long insert(String sql,Object... args){KeyHolder keys=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},keys);return Objects.requireNonNull(keys.getKey()).longValue();}
    private int count(String sql,Object... args){Integer i=jdbc.queryForObject(sql,Integer.class,args);return i==null?0:i;}
    private void validateDuration(int d){if(d!=30&&d!=60)throw new IllegalArgumentException("Duración debe ser 30 o 60 minutos");}
    private SchedulingFailure notFound(String s){return new SchedulingFailure(SchedulingFailure.Kind.NOT_FOUND,s+" no encontrado");} private SchedulingFailure conflict(String s){return new SchedulingFailure(SchedulingFailure.Kind.CONFLICT,s);} private Object[] concat(Object first,List<Long> rest){Object[] r=new Object[rest.size()+1];r[0]=first;for(int i=0;i<rest.size();i++)r[i+1]=rest.get(i);return r;}
}
